---
LineLength:
  Max: 120
Style/FileName:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/Semicolon:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space
Style/TrailingCommaInLiteral:
  Enabled: false
